// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.TipCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("bill_amount")]
        public long BillAmount { get; set; }

        [JsonProperty("tip_percentage")]
        public long TipPercentage { get; set; }

        [JsonProperty("tip_amount")]
        public long TipAmount { get; set; }

        [JsonProperty("total_amount")]
        public long TotalAmount { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("split_between")]
        public long SplitBetween { get; set; }

        [JsonProperty("per_person")]
        public PerPerson PerPerson { get; set; }

        [JsonProperty("common_tip_amounts")]
        public CommonTipAmount[] CommonTipAmounts { get; set; }
    }

    public partial class CommonTipAmount
    {
        [JsonProperty("percentage")]
        public long Percentage { get; set; }

        [JsonProperty("tip_amount")]
        public long TipAmount { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("per_person")]
        public double PerPerson { get; set; }
    }

    public partial class PerPerson
    {
        [JsonProperty("bill_amount")]
        public long BillAmount { get; set; }

        [JsonProperty("tip_amount")]
        public double TipAmount { get; set; }

        [JsonProperty("total_amount")]
        public double TotalAmount { get; set; }
    }
}
